name: spotify
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  build_runner: ^2.4.12
  shared_preferences: ^2.3.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  dotted_border: ^2.1.0
  flex_color_picker: ^3.5.1
  file_picker: ^8.1.2
  audio_waveforms: ^1.0.5
  just_audio: ^0.9.40

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
